apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: apic-demo-listener
  name: apic-demo-webhook
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-apic-demo-listener